# http://www.appveyor.com/docs/appveyor-yml

# configuration for develop/CI and master/Release branch

branches:
  only:
    - dev
    - master

skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
test: off

# Install dotnet core 3.0 latest (alpha!!), as this is not provided on AppVeyor yet
install:
  # Install Microsoft Windows SDK for Windows 10 and .NET Framework 4.7 10.1.17763.1
  - cinst windows-sdk-10-version-1809-all --version 10.0.17763.1
  - cinst windows-sdk-10-version-1809-all
  #- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe'
  #- ps: Start-Process .\dotnet-sdk-latest-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
  #- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/3.0.100-preview4-010538/dotnet-sdk-3.0.100-preview4-010538-win-x64.exe'
  #- ps: Start-Process .\dotnet-sdk-3.0.100-preview4-010538-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
  #- ps: Start-FileDownload 'https://download.visualstudio.microsoft.com/download/pr/4032ceb5-61cd-495a-ab25-475aa2232f28/7eb614e777d87ef0d49f86be4fc8bbde/dotnet-sdk-3.0.100-preview4-011223-win-x64.exe'
  #- ps: Start-Process .\dotnet-sdk-3.0.100-preview4-011223-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
  - cinst dotnetcore-sdk --pre

pull_requests:
  do_not_increment_build_number: false

build_script:
  - ps: cd src
  - ps: .\build.ps1 --bootstrap
  - ps: .\build.ps1 -target appveyor
  - ps: cd..

artifacts:
  - path: \src\Publish\*.*

nuget:
  disable_publish_on_pr: true